-- =============================================================================
-- Catálogo REAL de Nateco (pxw.com.ar/Nateco), relevado el 02/09/2026.
-- Reemplaza el catálogo de ejemplo por el catálogo completo real (18 rubros,
-- 255 productos). Corré esto en Supabase → SQL Editor.
-- =============================================================================

delete from products;

insert into products (id, name, category, unit, price, desde, stock, featured, art) values
('fc01', '1/2Kg Mix Açai con Banana y Frutilla', 'frutas-congeladas', '-', 9500, false, true, false, 'berry'),
('fc02', '1kg Mix Patagonico', 'frutas-congeladas', '-', 17900, false, true, false, 'berry'),
('fc03', 'Mix Frutos Rojos', 'frutas-congeladas', '-', 10500, true, true, false, 'berry'),
('fc04', 'Mix Frutos del Bosque', 'frutas-congeladas', '-', 9500, true, true, false, 'berry'),
('fc05', 'Mix Tucumano', 'frutas-congeladas', '-', 14900, true, true, false, 'berry'),
('fc06', 'Mix Caribe', 'frutas-congeladas', '-', 8900, true, true, false, 'berry'),
('fc07', '1/2kg Frambuesas IQF', 'frutas-congeladas', '-', 14900, false, false, false, 'berry'),
('fc08', '1/2kg Moras', 'frutas-congeladas', '-', 8200, false, false, false, 'berry'),
('fc09', 'Arándanos', 'frutas-congeladas', '-', 9200, true, true, false, 'berry'),
('fc10', 'Frutilla entera', 'frutas-congeladas', '-', 6500, true, true, false, 'berry'),
('fc11', 'Mango en cubos', 'frutas-congeladas', '-', 8500, true, true, false, 'berry'),
('fc12', '1/2kg Ananá', 'frutas-congeladas', '-', 8900, false, false, false, 'berry'),
('fc13', '1/2kg Maracuyá en cubos', 'frutas-congeladas', '-', 10500, false, true, false, 'berry'),
('vc01', 'Mix Cebolla y Pimientos', 'verduras-congeladas', '-', 6900, true, true, false, 'herb'),
('vc02', 'Wok de Vegetales', 'verduras-congeladas', '-', 6900, true, true, false, 'herb'),
('vc03', 'Mix Sopa de Vegetales', 'verduras-congeladas', '-', 6900, true, true, false, 'herb'),
('vc04', '1kg de Mix de Lentejas', 'verduras-congeladas', '-', 10900, false, true, false, 'herb'),
('vc05', '1Kg Mix nutritivo para tarta de Espinaca', 'verduras-congeladas', '-', 11500, false, false, false, 'herb'),
('vc06', '1/2kg Mix Hongos', 'verduras-congeladas', '-', 6500, false, false, false, 'herb'),
('vc07', 'Champiñones', 'verduras-congeladas', '-', 8500, true, true, false, 'herb'),
('vc08', '1/2kg Pulpa de Palta', 'verduras-congeladas', '-', 9900, false, true, false, 'herb'),
('vc09', '1/2kg Palta en Mitades', 'verduras-congeladas', '-', 10500, false, true, false, 'herb'),
('vc10', '1/2Kg Esparragos', 'verduras-congeladas', '-', 10800, false, false, false, 'herb'),
('vc11', '1/2kg Habas', 'verduras-congeladas', '-', 7200, false, true, false, 'herb'),
('vc12', 'Brocoli', 'verduras-congeladas', '-', 5800, true, true, false, 'herb'),
('vc13', '1Kg Espinaca en hojas cortadas', 'verduras-congeladas', '-', 10800, false, true, false, 'herb'),
('vc14', 'Espinaca en porciones', 'verduras-congeladas', '-', 5700, true, true, false, 'herb'),
('vc15', 'Cebolla', 'verduras-congeladas', '-', 5100, true, true, false, 'herb'),
('vc16', 'Morron', 'verduras-congeladas', '-', 5800, true, true, false, 'herb'),
('vc17', '700G Papa Baston', 'verduras-congeladas', '-', 5900, false, true, false, 'herb'),
('vc18', '500 g Zuquini en cubos', 'verduras-congeladas', '-', 5800, false, true, false, 'herb'),
('vc19', 'Zanahoria en cubos', 'verduras-congeladas', '-', 4100, true, true, false, 'herb'),
('vc20', '1Kg Batata en Cubos', 'verduras-congeladas', '-', 7600, false, false, false, 'herb'),
('vc21', 'Zapallo en cubos', 'verduras-congeladas', '-', 8500, true, true, false, 'herb'),
('vc22', 'Choclo', 'verduras-congeladas', '-', 5600, true, true, false, 'herb'),
('vc23', 'Arveja', 'verduras-congeladas', '-', 6200, true, true, false, 'herb'),
('vc24', '1/2kg Chauchas', 'verduras-congeladas', '-', 6200, false, true, false, 'herb'),
('cc01', 'Empanadas Mix Veggie Precocidas y congeladas x6 unidades', 'comidas-congeladas', '-', 11900, false, true, false, 'nut'),
('cc02', 'Tartas Listas', 'comidas-congeladas', '-', 8500, true, true, false, 'nut'),
('cc03', 'Tequenos TequePops x12 Unidades', 'comidas-congeladas', '-', 13500, false, true, false, 'nut'),
('cc04', 'Milanesas de Soja Rellenas', 'comidas-congeladas', '-', 6500, true, true, false, 'nut'),
('cc05', 'Milanesas de Seitan', 'comidas-congeladas', '-', 6500, false, true, false, 'nut'),
('cc06', 'Bastones de Muzzarella 500Gr', 'comidas-congeladas', '-', 7900, false, true, false, 'nut'),
('cc07', 'Bocaditos Listos', 'comidas-congeladas', '-', 4500, true, true, false, 'nut'),
('cc08', 'Hamburguesas Nutree', 'comidas-congeladas', '-', 6900, true, true, false, 'nut'),
('fs01', 'Nuez Chandler Extra Ligth', 'frutos-secos', '-', 5600, true, true, false, 'nut'),
('fs02', 'Nuez Extra Ligth PARTIDA', 'frutos-secos', '-', 5500, true, true, false, 'nut'),
('fs03', 'Nuez PECAN Pelada', 'frutos-secos', '-', 8100, true, true, false, 'nut'),
('fs04', 'Castañas de Caju W3', 'frutos-secos', '-', 6100, true, true, false, 'nut'),
('fs05', 'Castañas De Caju TOSTADAS', 'frutos-secos', '-', 6500, true, true, false, 'nut'),
('fs06', 'Castañas De Pará', 'frutos-secos', '-', 10800, true, true, false, 'nut'),
('fs07', 'Almendra non pareil', 'frutos-secos', '-', 7600, true, true, false, 'nut'),
('fs08', 'Almendras Guara Nacional', 'frutos-secos', '-', 6800, true, true, false, 'nut'),
('fs09', 'Pistachos Con Cascaras', 'frutos-secos', '-', 10500, true, true, false, 'nut'),
('fs10', 'Pistachos Pelados', 'frutos-secos', '-', 19500, true, true, false, 'nut'),
('fs11', 'Avellanas', 'frutos-secos', '-', 10400, true, true, false, 'nut'),
('fs12', 'Mani Tostado Sin Sal', 'frutos-secos', '-', 3100, true, true, false, 'nut'),
('fs13', 'Maní Tostado Salado', 'frutos-secos', '-', 3200, true, true, false, 'nut'),
('mfs01', 'Mix Premium', 'mix-frutos-secos', '-', 7000, true, true, false, 'nut'),
('mfs02', 'Mix Premium Con Avellanas', 'mix-frutos-secos', '-', 7500, true, true, false, 'nut'),
('mfs03', 'Mix Premium Con Arandanos', 'mix-frutos-secos', '-', 6500, true, true, false, 'nut'),
('mfs04', 'Mix Premium Con Mani', 'mix-frutos-secos', '-', 4500, true, true, false, 'nut'),
('mfs05', 'Mix Premium Con Pasas', 'mix-frutos-secos', '-', 5000, true, true, true, 'nut'),
('mfs06', 'Mix Energético', 'mix-frutos-secos', '-', 3600, true, true, false, 'nut'),
('mfs07', 'Mix Salado', 'mix-frutos-secos', '-', 3900, true, true, false, 'nut'),
('mfs08', 'Maiz Frito Mostaza y Miel', 'mix-frutos-secos', '-', 4200, true, true, false, 'nut'),
('mfs09', 'Mix Tropical Premium', 'mix-frutos-secos', '-', 5100, true, true, false, 'nut'),
('mfs10', 'Mix Araucano', 'mix-frutos-secos', '-', 5000, true, true, false, 'nut'),
('fd01', 'Arándanos', 'frutas-desecadas', '-', 5100, true, true, false, 'berry'),
('fd02', 'Pasas de uva Jumbo', 'frutas-desecadas', '-', 2500, true, true, false, 'berry'),
('fd03', 'Pasas de uva Rubias', 'frutas-desecadas', '-', 3000, true, true, false, 'berry'),
('fd04', 'Bananitas chip', 'frutas-desecadas', '-', 4200, true, true, false, 'berry'),
('fd05', 'Ciruelas Bombón', 'frutas-desecadas', '-', 3700, true, true, false, 'berry'),
('fd06', 'Ciruela Presidente', 'frutas-desecadas', '-', 5100, true, true, false, 'berry'),
('fd07', 'Peras', 'frutas-desecadas', '-', 4500, true, true, false, 'berry'),
('fd08', 'Duraznos Medallones', 'frutas-desecadas', '-', 5100, true, true, false, 'berry'),
('fd09', 'Higos Negros', 'frutas-desecadas', '-', 4300, true, true, false, 'berry'),
('fd10', 'Dátiles Medjool', 'frutas-desecadas', '-', 7700, true, true, false, 'berry'),
('fd11', 'Datiles Deglet Nour Premium', 'frutas-desecadas', '-', 3800, true, true, false, 'berry'),
('fd12', 'Coco Rallado', 'frutas-desecadas', '-', 3900, true, true, false, 'berry'),
('fd13', 'Hongos De Pino', 'frutas-desecadas', '-', 4800, true, true, false, 'berry'),
('fd14', 'Tomates Desecados', 'frutas-desecadas', '-', 5100, true, true, false, 'berry'),
('gc01', 'Granola Crocante', 'granolas-cereales', '-', 6400, true, true, false, 'nut'),
('gc02', 'Granola Energética', 'granolas-cereales', '-', 5400, true, true, false, 'nut'),
('gc03', 'Granola con Arándanos Premium', 'granolas-cereales', '-', 6400, true, true, false, 'nut'),
('gc04', 'Granola Patagónica', 'granolas-cereales', '-', 5900, true, true, false, 'nut'),
('gc05', 'Granola Del Valle', 'granolas-cereales', '-', 5900, true, true, false, 'nut'),
('gc06', 'Quinoa Pop', 'granolas-cereales', '-', 3700, true, true, false, 'nut'),
('gc07', 'Avena Instantánea', 'granolas-cereales', '-', 2200, true, true, false, 'nut'),
('gc08', 'Avena Instantánea 350g - SIN GLUTEN', 'granolas-cereales', '-', 3300, false, true, false, 'nut'),
('gc09', 'Bolitas de cereal con chocolate', 'granolas-cereales', '-', 2300, true, true, false, 'nut'),
('gc10', 'Almohaditas', 'granolas-cereales', '-', 2900, true, true, false, 'nut'),
('gc11', 'Anillos de Avena y Miel', 'granolas-cereales', '-', 2600, true, true, false, 'nut'),
('gc12', 'Copos de Maíz Sin Azúcar', 'granolas-cereales', '-', 4200, true, true, false, 'nut'),
('hf01', 'Harina de Arvejas 450g - SIN GLUTEN', 'harinas-fecula', '-', 2900, false, true, false, 'nut'),
('hf02', 'Harina de Trigo Sarraceno Orgánico 450g - SIN GLUTEN', 'harinas-fecula', '-', 3900, false, true, false, 'nut'),
('hf03', '1kg Harina Integral De Trigo Organica', 'harinas-fecula', '-', 3900, false, true, false, 'nut'),
('hf04', '1kg Harina Integral De Centeno Organica', 'harinas-fecula', '-', 4300, false, true, false, 'nut'),
('hf05', '1kg Harina Integral De Cebada Organica', 'harinas-fecula', '-', 4300, false, true, false, 'nut'),
('hf06', 'Harina de Almendras con Piel', 'harinas-fecula', '-', 5500, true, true, false, 'nut'),
('hf07', 'Harina de Almendras Sin Piel 100%', 'harinas-fecula', '-', 14500, true, true, false, 'nut'),
('hf08', 'Harina de Avena', 'harinas-fecula', '-', 2100, true, true, false, 'nut'),
('hf09', 'Harina de coco', 'harinas-fecula', '-', 4600, true, true, false, 'nut'),
('hf10', 'Harina de Garbanzos', 'harinas-fecula', '-', 1900, true, true, false, 'nut'),
('hf11', 'Harina de Arroz', 'harinas-fecula', '-', 1500, true, true, false, 'nut'),
('hf12', 'Lino Molino', 'harinas-fecula', '-', 2100, true, true, false, 'nut'),
('hf13', 'Fécula de mandioca a granel - Sin TACC', 'harinas-fecula', '-', 2300, true, true, false, 'nut'),
('hf14', 'Polvo Para Hornear - Dicomere', 'harinas-fecula', '-', 6500, false, true, false, 'nut'),
('hf15', 'Almidon de Maiz Glutal x200g', 'harinas-fecula', '-', 1900, false, false, false, 'nut'),
('hf16', 'Rebozador Glutal SIN GLUTEN x500g', 'harinas-fecula', '-', 3900, false, true, false, 'nut'),
('hf17', 'Premezcla Pan Dicomere -SIN GLUTEN x450g', 'harinas-fecula', '-', 3500, false, true, false, 'nut'),
('hf18', 'Premezcla Pan Integral Delicel SIN GLUTEN 500g', 'harinas-fecula', '-', 4200, false, true, false, 'nut'),
('hf19', 'Premezcla Para Pizza Delicel SIN GLUTEN 500g', 'harinas-fecula', '-', 3900, false, true, false, 'nut'),
('af01', 'Arroz Yamani Integral', 'arroz-fideos', '-', 1800, true, true, false, 'nut'),
('af02', 'Arroz Largo Fino Integral', 'arroz-fideos', '-', 1500, true, true, false, 'nut'),
('af03', 'Arroz Basmati', 'arroz-fideos', '-', 3500, true, true, false, 'nut'),
('af04', 'Arroz Carnaroli', 'arroz-fideos', '-', 2500, true, true, false, 'nut'),
('af05', 'Arroz Largo Fino Blanco', 'arroz-fideos', '-', 1500, true, true, false, 'nut'),
('af06', 'Fideos Wakas', 'arroz-fideos', '-', 3500, true, true, false, 'nut'),
('af07', 'Fideos de Arroz Natural x 300g', 'arroz-fideos', '-', 3900, false, true, false, 'nut'),
('af08', 'Polenta Organica SIN TACC x450g', 'arroz-fideos', '-', 2400, false, true, false, 'nut'),
('sm01', 'Semillas De Girasol', 'semillas', '-', 2000, true, true, false, 'herb'),
('sm02', 'Semillas De Zapallo', 'semillas', '-', 4600, true, true, false, 'herb'),
('sm03', 'Semillas De Chia', 'semillas', '-', 2900, true, true, false, 'herb'),
('sm04', 'Semillas de Zaragatona (Psyllium)', 'semillas', '-', 4900, true, true, false, 'herb'),
('sm05', 'Semillas De Sesamo Integral', 'semillas', '-', 1600, true, true, false, 'herb'),
('sm06', 'Sesamo Negro', 'semillas', '-', 2400, true, true, false, 'herb'),
('sm07', 'Semillas De Lino', 'semillas', '-', 1200, true, true, false, 'herb'),
('sm08', 'Mix De Semillas', 'semillas', '-', 3700, true, true, false, 'herb'),
('sm09', 'Semilla de Amaranto', 'semillas', '-', 1900, true, true, false, 'herb'),
('sm10', 'Quinoa Blanca', 'semillas', '-', 5700, true, true, false, 'herb'),
('sm11', 'Mix de sesamo', 'semillas', '-', 4100, true, true, false, 'herb'),
('lg01', 'Lentejón Nacional', 'legumbres', '-', 2600, true, true, false, 'nut'),
('lg02', 'Texturizado de Soja Grueso', 'legumbres', '-', 1900, true, true, false, 'nut'),
('lg03', 'Lenteja', 'legumbres', '-', 2200, true, true, false, 'nut'),
('lg04', 'Garbanzo', 'legumbres', '-', 1900, true, true, false, 'nut'),
('lg05', 'Arvejas Enteras', 'legumbres', '-', 1300, true, true, false, 'nut'),
('lg06', 'Poroto Colorado', 'legumbres', '-', 2700, true, true, false, 'nut'),
('lg07', 'Poroto Negro', 'legumbres', '-', 2200, true, true, false, 'nut'),
('lg08', 'Poroto Aduki', 'legumbres', '-', 1900, true, true, false, 'nut'),
('lg09', 'Poroto Mung', 'legumbres', '-', 1900, true, true, false, 'nut'),
('lg10', 'Poroto Alubia', 'legumbres', '-', 2200, true, true, false, 'nut'),
('lg11', 'Porotos Pallares', 'legumbres', '-', 4500, true, true, false, 'nut'),
('lg12', 'Lenteja Turca', 'legumbres', '-', 3600, true, true, false, 'nut'),
('es01', 'Pimienta Negra', 'especias', '-', 4900, true, true, false, 'herb'),
('es02', 'Pimienta Blanca', 'especias', '-', 5700, true, true, false, 'herb'),
('es03', 'Mix De Pimientas en Grano', 'especias', '-', 5900, true, true, false, 'herb'),
('es04', 'Nuez Moscada Molida', 'especias', '-', 4300, true, true, false, 'herb'),
('es05', 'Pimentón', 'especias', '-', 2500, true, true, false, 'herb'),
('es06', 'Pimenton Ahumado', 'especias', '-', 3500, true, true, false, 'herb'),
('es07', 'Curry', 'especias', '-', 1900, true, true, false, 'herb'),
('es08', 'Garam Masala', 'especias', '-', 3000, true, true, false, 'herb'),
('es09', 'Ajo en Polvo', 'especias', '-', 1900, true, true, false, 'herb'),
('es10', 'Aji Molido', 'especias', '-', 2500, true, true, false, 'herb'),
('es11', 'Oregano', 'especias', '-', 1200, true, true, false, 'herb'),
('es12', 'Adobo para Pizza', 'especias', '-', 1200, true, true, false, 'herb'),
('es13', '100g Chimichurri', 'especias', '-', 2000, false, true, false, 'herb'),
('es14', 'Tomillo', 'especias', '-', 1900, true, true, false, 'herb'),
('es15', 'Romero', 'especias', '-', 1500, true, true, false, 'herb'),
('es16', 'Comino Molido Especial', 'especias', '-', 3500, true, true, false, 'herb'),
('es17', 'Canela Molida', 'especias', '-', 3900, true, true, false, 'herb'),
('es18', 'Curcuma', 'especias', '-', 3500, true, true, false, 'herb'),
('ib01', 'Combo Matero (300g)', 'infusiones-bebidas', '-', 10000, false, true, false, 'herb'),
('ib02', 'Flor De Hibiscus', 'infusiones-bebidas', '-', 6000, true, true, true, 'herb'),
('ib03', 'Manzanilla', 'infusiones-bebidas', '-', 4200, true, true, true, 'herb'),
('ib04', '100g Burrito en Hoja', 'infusiones-bebidas', '-', 3000, false, true, true, 'herb'),
('ib05', '100 g Boldo', 'infusiones-bebidas', '-', 3500, false, true, true, 'herb'),
('ib06', '100 g Poleo', 'infusiones-bebidas', '-', 3500, false, true, true, 'herb'),
('ib07', 'Calendula', 'infusiones-bebidas', '-', 2000, true, true, true, 'herb'),
('ib08', 'Te verde', 'infusiones-bebidas', '-', 1400, true, true, false, 'herb'),
('ib09', 'Yerba mate', 'infusiones-bebidas', '-', 3900, true, true, false, 'herb'),
('ib10', 'TE HEREDIA', 'infusiones-bebidas', '-', 3100, true, true, false, 'herb'),
('ib11', 'Bolsa para leches vegetales', 'infusiones-bebidas', '-', 4700, false, true, false, 'herb'),
('ib12', 'Leches Vegetales', 'infusiones-bebidas', '-', 5900, true, true, false, 'herb'),
('ib13', 'Leche de coco en polvo', 'infusiones-bebidas', '-', 6900, true, true, false, 'herb'),
('ch01', 'Cacao Amargo en Polvo x100g', 'chocolates-confitados', '-', 2900, false, true, false, 'berry'),
('ch02', 'Chocolate Aguila', 'chocolates-confitados', '-', 6500, true, true, false, 'berry'),
('ch03', 'Chips de Chocolate Semi Amargo', 'chocolates-confitados', '-', 3700, true, true, false, 'berry'),
('ch04', 'Almendras con Chocolate', 'chocolates-confitados', '-', 8300, true, true, false, 'berry'),
('ch05', 'Mani Con Chocolate', 'chocolates-confitados', '-', 5800, true, true, false, 'berry'),
('ch06', 'Arándanos Con Chocolate', 'chocolates-confitados', '-', 7900, true, true, false, 'berry'),
('ch07', 'Arándanos con chocolate Blanco y Yogurt', 'chocolates-confitados', '-', 7900, true, true, false, 'berry'),
('ch08', 'Pasas De Uva Con Chocolate', 'chocolates-confitados', '-', 6400, true, true, false, 'berry'),
('ch09', 'Cereal Con Chocolate', 'chocolates-confitados', '-', 7100, true, true, false, 'berry'),
('ch10', 'Garrapiñada de Almendras', 'chocolates-confitados', '-', 6500, true, true, false, 'berry'),
('ch11', 'Garrapiñada de Mani', 'chocolates-confitados', '-', 2900, true, true, false, 'berry'),
('al01', 'Aceite de Chia 150cc Solazteca', 'almacen', '-', 8900, false, true, false, 'supp'),
('al02', 'Aceite de Sesamo 150cc Sol azteca', 'almacen', '-', 6500, false, true, false, 'supp'),
('al03', 'Pancakes Proteicos', 'almacen', '-', 13900, true, true, true, 'supp'),
('al04', 'Barritas Proteicas Naturales', 'almacen', '-', 2100, true, true, false, 'supp'),
('al05', 'Miel', 'almacen', '-', 6000, true, true, false, 'supp'),
('al06', 'Pasta de Castañas de Caju Dicomere x170g', 'almacen', '-', 7800, false, true, true, 'supp'),
('al07', 'Manteca de Mani', 'almacen', '-', 3800, true, true, false, 'supp'),
('al08', 'Aceite de Oliva', 'almacen', '-', 16500, true, true, false, 'supp'),
('al09', 'Aceite de Coco', 'almacen', '-', 7800, true, true, false, 'supp'),
('al10', 'GHEE Manteca Clarificada x 300g - EntreNuts', 'almacen', '-', 12500, false, true, false, 'supp'),
('al11', 'Vinagre de Sidra de Manzana Orgánico 250g', 'almacen', '-', 8500, false, false, false, 'supp'),
('al12', 'Salsa de Soja', 'almacen', '-', 4100, true, true, false, 'supp'),
('al13', 'Levadura Nutricional', 'almacen', '-', 11200, true, true, false, 'supp'),
('al14', 'Azucar Mascabo', 'almacen', '-', 3500, true, true, false, 'supp'),
('al15', 'Stevia Dulri Natural', 'almacen', '-', 3100, false, true, false, 'supp'),
('al16', 'Sal Marina Fina 450g- SIN TACC', 'almacen', '-', 2500, false, true, false, 'supp'),
('al17', 'Sal Marina Gruesa 450g -SIN TACC', 'almacen', '-', 2500, false, true, false, 'supp'),
('al18', 'Sal Rosa Fina Del Himalaya', 'almacen', '-', 1900, true, true, false, 'supp'),
('al19', 'Sal Sin Sodio 70g - Salusin', 'almacen', '-', 3900, false, true, false, 'supp'),
('al20', 'Bicarbonato de sodio x 200g - SIN TACC', 'almacen', '-', 2500, false, true, false, 'supp'),
('al21', 'Gelatina Sin Sabor', 'almacen', '-', 7800, true, true, false, 'supp'),
('al22', 'Cous Cous 500g', 'almacen', '-', 5500, false, true, false, 'supp'),
('al23', 'Galletas de arroz SIN SAL', 'almacen', '-', 2100, false, true, false, 'supp'),
('al24', 'Galletas de arroz CON SAL', 'almacen', '-', 2200, false, true, false, 'supp'),
('al25', 'Dulces Caseros Regionales', 'almacen', '-', 9900, true, true, false, 'supp'),
('al26', 'Gift Card Saludable', 'almacen', '-', 30000, false, true, false, 'supp'),
('su01', 'COMBO GOLD: Proteina + Creatina', 'suplementos', '-', 97900, false, true, false, 'supp'),
('su02', 'COMBO STAR: Proteina + Creatina', 'suplementos', '-', 97500, false, true, false, 'supp'),
('su03', 'Whey Protein Bar - Mervick Lab', 'suplementos', '-', 2500, true, true, false, 'supp'),
('su04', 'Creatinas', 'suplementos', '-', 15900, true, true, false, 'supp'),
('su05', 'Aminoacidos Bcaa 8.1.1 Gold Nutrition 280g', 'suplementos', '-', 29000, false, true, false, 'supp'),
('su06', 'Whey Protein Gold Nutrition 2LBS', 'suplementos', '-', 75000, true, true, false, 'supp'),
('su07', 'Whey Protein Star Nutrition 2LBS', 'suplementos', '-', 73000, true, true, false, 'supp'),
('su08', 'Just Plant Protein Star Nutrition 2LB', 'suplementos', '-', 49000, false, true, true, 'supp'),
('su09', 'Geomagnesium Total Geonat 150g', 'suplementos', '-', 14000, false, false, false, 'supp'),
('su10', 'Citrato de Magnesio Geonat 500 30caps', 'suplementos', '-', 10500, false, true, false, 'supp'),
('su11', 'Omega 3 Geonat Omeganat Aceite De Pescado - 60 caps', 'suplementos', '-', 22000, false, true, false, 'supp'),
('su12', 'Colageno Geonat 500 - 60cap.', 'suplementos', '-', 12000, false, true, false, 'supp'),
('su13', 'Curcumin Asian Geonat - 30 caps', 'suplementos', '-', 11500, false, true, false, 'supp'),
('su14', 'Aceite De Orégano Geonat - 30ml', 'suplementos', '-', 19000, false, true, false, 'supp'),
('su15', 'Probioticos Geonat Lactobasillus - 30caps', 'suplementos', '-', 16000, false, true, false, 'supp'),
('su16', 'Probióticos KYOJIN - 60 ml', 'suplementos', '-', 16000, false, true, false, 'supp'),
('su17', 'Membrillitos Profecía CAJA x28u 30g', 'suplementos', '-', 15000, false, true, false, 'supp'),
('su18', 'Membrillitos Profecía x5unidades 30g', 'suplementos', '-', 4500, false, true, false, 'supp'),
('co01', 'Bálsamo Labial - CHERRY - Naturalu', 'cosmetica-higiene', '-', 9500, false, true, false, 'supp'),
('co02', 'Aceite esencial de Lavanda Alquimia Artesanal', 'cosmetica-higiene', '-', 19000, false, true, false, 'supp'),
('co03', 'Aceite Orgánico de Rosa Mosqueta', 'cosmetica-higiene', '-', 15500, false, false, false, 'supp'),
('co04', 'Aceite esencial de Romero Alquimia Artesanal', 'cosmetica-higiene', '-', 16000, false, true, false, 'supp'),
('co05', 'Bálsamo Labial Alquimia Artesanal', 'cosmetica-higiene', '-', 6400, false, true, false, 'supp'),
('co06', 'Cepillo Dental de Bambú Alquimia Artesanal', 'cosmetica-higiene', '-', 3900, false, true, false, 'supp'),
('co07', 'COMBO: Cepillo Dental de Bambú + Pasta Dental', 'cosmetica-higiene', '-', 10000, false, true, false, 'supp'),
('co08', 'Sérum Facial Nocturno Alquimia Artesanal', 'cosmetica-higiene', '-', 16900, false, true, false, 'supp'),
('co09', 'Jabones Alquimia Artesanal', 'cosmetica-higiene', '-', 6900, true, true, false, 'supp'),
('co10', 'Shampoo Solido Alquimia Artesanal', 'cosmetica-higiene', '-', 9800, true, true, false, 'supp'),
('co11', 'Acondicionador Sólido Alquimia Artesanal', 'cosmetica-higiene', '-', 9800, false, true, false, 'supp'),
('co12', 'Bolsas de Lienzo', 'cosmetica-higiene', '-', 1900, true, true, false, 'supp'),
('of01', 'OFERTA Tarta Caprese', 'ofertas', '-', 6900, false, true, false, 'berry'),
('of02', 'Aceite de COCO Virgen x200cc', 'ofertas', '-', 6900, false, true, false, 'berry'),
('of03', 'OFERTA Tarta Mixta Integral Calabaza y Acelga', 'ofertas', '-', 6900, false, true, false, 'berry'),
('of04', 'COMBO MENSUAL (13 productos)', 'ofertas', '-', 65000, false, true, false, 'berry'),
('of05', 'MENU SEMANAL', 'ofertas', '-', 36000, false, true, false, 'berry'),
('of06', 'OFERTA! x2kg Nuez Chandler Extra Ligth', 'ofertas', '-', 40000, false, true, false, 'berry'),
('of07', 'OFERTA! 2kg Almendra Non Pareil', 'ofertas', '-', 54000, false, true, false, 'berry'),
('of08', 'OFERTA! 2kg Castañas de Caju', 'ofertas', '-', 42800, false, true, false, 'berry'),
('of09', 'Combo: Flor de Hibiscus + Gelatina sin sabor', 'ofertas', '-', 24000, true, true, false, 'berry'),
('of10', 'Yerba Grapia Milenaria x1kg', 'ofertas', '-', 6450, false, true, false, 'berry'),
('of11', 'Pasta seca Artesanal', 'ofertas', '-', 5200, true, true, false, 'berry'),
('of12', 'Premezcla Bizcochuelo Chocolate Delicel SIN GLUTEN 500g', 'ofertas', '-', 3000, false, true, false, 'berry'),
('of13', 'Protector Solar (150gr)', 'ofertas', '-', 12000, false, true, false, 'berry');

-- Total: 255 productos
